### ISSUE TITLE
[Feature] Please make the 'MicroG Settings' application that is normally part of a microG install available

### ISSUE THREAD

**Issue by dperson** [FuriLabs/andromeda#2]
### Is your feature request related to a problem? Please describe.

Certain apps don't work with the Android emulation.

### Describe the solution you'd like.

MicroG Settings let's you at least see what "Self-Check" items it thinks have issues and remediate many of them.

### Describe alternatives you've considered.

I've thought about trying to extract it from the download and sideload it, but think that it probably has to be a System application.

### Additional context

Thank you for the great work, the phone is great and you've done a great job integrating the android apps with the rest of the device!

**Comment by FakeShell** [comment]
the microG settings app is actually included in the install, but its not visible in the app drawer. this months release will add an expander row in android app panel in settings which allows to open hidden apps

**Comment by dperson** [comment]
Perfect! That will fully resolve the request. Thanks for the awesome work!

**Comment by FakeShell** [comment]
can we close this? it should be resolved now.
